#define PROTEUS_KEYWORDS @[\
    @"and", \
    @"as", \
    @"assert", \
    @"break", \
    @"class", \
    @"continue", \
    @"def", \
    @"del", \
    @"elif", \
    @"else", \
    @"enum", \
    @"except", \
    @"exec", \
    @"finally", \
    @"for", \
    @"from", \
    @"global", \
    @"if", \
    @"import", \
    @"in", \
    @"is", \
    @"lamdba", \
    @"module", \
    @"namespace", \
    @"not", \
    @"or", \
    @"pass", \
    @"print", \
    @"raise", \
    @"return", \
    @"try", \
    @"while", \
    @"with", \
    @"yield" \
]
